"""Create BusinessDetails table

Revision ID: 1b8e8558158f
Revises: 95c077f78919
Create Date: 2024-09-02 12:28:29.380128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8e8558158f'
down_revision = '95c077f78919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=128), nullable=True),
    sa.Column('business_type', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('mission_statement', sa.Text(), nullable=True),
    sa.Column('vision_statement', sa.Text(), nullable=True),
    sa.Column('founded', sa.Integer(), nullable=True),
    sa.Column('founders', sa.String(length=256), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('number_of_employees', sa.Integer(), nullable=True),
    sa.Column('business_stage', sa.String(length=128), nullable=True),
    sa.Column('business_model', sa.String(length=128), nullable=True),
    sa.Column('turnover_year1', sa.Float(), nullable=True),
    sa.Column('turnover_year2', sa.Float(), nullable=True),
    sa.Column('turnover_year3', sa.Float(), nullable=True),
    sa.Column('turnover_year4', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('monthly_inflow', sa.Float(), nullable=True),
    sa.Column('monthly_outflow', sa.Float(), nullable=True),
    sa.Column('monthly_cashflow', sa.Float(), nullable=True),
    sa.Column('fixed_expense1', sa.Float(), nullable=True),
    sa.Column('fixed_expense2', sa.Float(), nullable=True),
    sa.Column('fixed_expense3', sa.Float(), nullable=True),
    sa.Column('fixed_expense4', sa.Float(), nullable=True),
    sa.Column('variable_expenses', sa.Float(), nullable=True),
    sa.Column('cash_flow_projection', sa.Float(), nullable=True),
    sa.Column('overdraft_limit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.drop_index('ix_user_username')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_username', ['username'], unique=1)
        batch_op.create_index('ix_user_email', ['email'], unique=1)

    op.drop_table('business_details')
    # ### end Alembic commands ###
